### ISSUE TITLE
Series of symbol will create correct chart

### ISSUE THREAD

**Issue by svlstriker** [lavolp3/MMM-AVStock#18]
I have a strange problem by using the series mode with the symbol "LHA.DE" (deutsche Lufthansa).
I only see a single bar in the chart. I testet it with the symbol "GOOGL" (like in the example) as well and there I get a nice chart as it should look like. 

Do you know, where the problem is? 
Are the data of LHA.DE in another format / formatted in another way, so the module can not create a nice view?

**Comment by lavolp3** [comment]
That's odd. The api output looks ok.
I would have to check that out in the module but I am not sure when I will have the time

**Comment by eouia** [comment]
Sorry, I have not enough time nowadays. Thanks to lavolp3.

@lavolp3  If you don't mind, I want to give the ownership of this repository. I hardly make a time to manage these MM projects at this moment.

**Comment by lavolp3** [comment]
How does that work? Can we transfer it to my account? 
Can you make me "owner" of the rep?

I can take over completely here, but I can only warn you: there's going to be a lot of changes :-)

**Comment by lavolp3** [comment]
> I have a strange problem by using the series mode with the symbol "LHA.DE" (deutsche Lufthansa).
> I only see a single bar in the chart. I testet it with the symbol "GOOGL" (like in the example) as well and there I get a nice chart as it should look like.
> 
> Do you know, where the problem is?
> Are the data of LHA.DE in another format / formatted in another way, so the module can not create a nice view?

Luckily I had the module still installed. It works for me.
![image](https://user-images.githubusercontent.com/20084205/81167301-4ba19080-8f95-11ea-9898-b91de563159e.png)
Can you post your config entry?

**Comment by eouia** [comment]
@lavolp3 Remove/rename your repository (lavolp3/MMM-AVStock) to move original to your account.

**Comment by svlstriker** [comment]
yes, for sure:

	// AKTIENKURSE
		{
			module: "MMM-AVStock",
			position: "top_left", //"bottom_bar" is better for `mode:ticker`
			config: {
				apiKey : "<my_key>", // https://www.alphavantage.co/
				timeFormat: "DD-MM-YYYY HH:mm:ss",
				symbols : ["LHA.DE"],
				alias: ["Lufthansa"], //Easy name of each symbol. When you use `alias`, the number of symbols and alias should be the same. If value is null or "", symbol string will be used by default.
//				tickerDuration: 60, // Ticker will be cycled once per this second.
				chartDays: 90, //For `mode:series`, how much daily data will be taken. (max. 90)
//				poolInterval : 1000*15, // (Changed in ver 1.1.0) - Only For Premium Account
				mode : "series", // "table", "ticker", "series"
				decimals: 4, // number o decimals for all values including decimals (prices, price changes, change%...)
				candleSticks : false, //show candle sticks if mode is Series
				coloredCandles : false, //colored bars: red and green for negative and positive candles
//				premiumAccount: false, // To change poolInterval, set this to true - Only For Premium Account
			}
		},

**Comment by svlstriker** [comment]
> 
> 
> > I have a strange problem by using the series mode with the symbol "LHA.DE" (deutsche Lufthansa).
> > I only see a single bar in the chart. I testet it with the symbol "GOOGL" (like in the example) as well and there I get a nice chart as it should look like.
> > Do you know, where the problem is?
> > Are the data of LHA.DE in another format / formatted in another way, so the module can not create a nice view?
> 
> Luckily I had the module still installed. It works for me.
> ![image](https://user-images.githubusercontent.com/20084205/81167301-4ba19080-8f95-11ea-9898-b91de563159e.png)
> Can you post your config entry?

**Comment by svlstriker** [comment]
damn it... miss-click...

here is my code:

```
		{
			module: "MMM-AVStock",
			position: "top_left", //"bottom_bar" is better for `mode:ticker`
			config: {
				apiKey : "<my_api_key>", // https://www.alphavantage.co/
				timeFormat: "DD-MM-YYYY HH:mm:ss",
				symbols : ["LHA.DE"],
				alias: ["Lufthansa"], //Easy name of each symbol. When you use `alias`, the number of symbols and alias should be the same. If value is null or "", symbol string will be used by default.
//				tickerDuration: 60, // Ticker will be cycled once per this second.
				chartDays: 90, //For `mode:series`, how much daily data will be taken. (max. 90)
//				poolInterval : 1000*15, // (Changed in ver 1.1.0) - Only For Premium Account
				mode : "series", // "table", "ticker", "series"
				decimals: 4, // number o decimals for all values including decimals (prices, price changes, change%...)
				candleSticks : false, //show candle sticks if mode is Series
				coloredCandles : false, //colored bars: red and green for negative and positive candles
//				premiumAccount: false, // To change poolInterval, set this to true - Only For Premium Account
			}
		},
```

**Comment by svlstriker** [comment]
I changed the timeFormat... maybe this is the problem?

**Comment by lavolp3** [comment]
> I changed the timeFormat... maybe this is the problem?

I can't imagine that being a problem.
But does it work now?

**Comment by svlstriker** [comment]
I still get a single bar shown...

could you send me your config part?
maybe I have any shitty character, that I do not see ...

**Comment by svlstriker** [comment]
here is how it should look like with aapl as symbol:
![grafik](https://user-images.githubusercontent.com/25102931/81175648-2b2d0280-8fa4-11ea-905e-9f435a95f6c9.png)

and this is the exact same code with LHA.DE as symbol:
![grafik](https://user-images.githubusercontent.com/25102931/81175553-059ff900-8fa4-11ea-9427-52bb5c96b37e.png)

if I switch to candleStickls and colored candleCandles set true, I get grey-white candles for APPLE and the same single bar for Lufthansa...
![grafik](https://user-images.githubusercontent.com/25102931/81176382-61b74d00-8fa5-11ea-8ea7-d8bf25470149.png)

Maybe there is any incompatibility or something else with my other installed modules?
- MMM-AVStock
- MMM-CountDown
- MMM-FRITZ-Box-Callmonitor
- MMM-Fuel
- MMM-RMV
- MMM-Wallpaper

**Comment by lavolp3** [comment]
can you look into 
```
pm2 logs
```
and search the error logs (red) for errors from this module?

And try limiting chartDays
```
chartDays: 45
```
That's what I had

**Comment by lavolp3** [comment]
> if I switch to candleStickls and colored candleCandles set true, I get grey-white candles for APPLE

Really? They should be coloured. coloredCandles is set true and they are grey-white?
I need to look into this as well.

**Comment by svlstriker** [comment]
okay an update:

I added some some symbols (each for another lufthansa station).
I sed 'candleSticks : true' and 'coloredCandles : true' as well.
Now I get 2 up to 5 single bars in green, red and somtimes thin white.

Maybe the scale is wrong?

testet symbols:
"LHA.DE", "LHA.BER", "DLAKY", "DLAKF", "LHA.DEX", "LHA.FRK", "LHA.STG", "LHA.VIE", "LHA.MIL"
chartDays: 45
mode: "series"

**Comment by lavolp3** [comment]
I will have to have a closer look into this. I'm on another branch so maybe there's an error in the master branch.
Give me some time.

**Comment by svlstriker** [comment]
yes for sure! you have all the time you need ;-)

btw: 
I am using Node.js v10.19.0, which is not supported by npm.
This will be shown at any start of MagicMirrir, but I did not get any problems (only now with AVStock and ONLY with Lufthansa...)

Here is the log:
0|mm  | npm
0|mm  |
0|mm  | WARN npm npm does not support Node.js v10.19.0
0|mm  | npm WARN npm You should probably upgrade to a newer version of node as we
0|mm  | npm WARN npm can't make any promises that npm will work with this version.
0|mm  | npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
0|mm  | npm WARN
0|mm  |  npm You can find the latest version at https://nodejs.org/

Nothing more error or warning messages...

I work with MMM-AVStock at master branch with commit 53c630005c3e47719815dc407630aef5c6a73d34

I removed nodejs v10.19.0 and installed nodejs v9.11.2 manually.
The error message of npm will not be shown anymore but my problem is still there.
So I do not think, that die problem comes from incompatible nodejs v10.
(I saw that nodejs v10 is preferred by installation guide https://docs.magicmirror.builders/getting-started/requirements.html#hardware)

More and more I think it is a problem with scaling...
GOOGL for example has a value of ~1350... lufthansa has only a value of ~8

Maybe the module scales only once for all symbols?

**Comment by lavolp3** [comment]
> I am using Node.js v10.19.0, which is not supported by npm.

It is not supported by YOUR VERSION of npm. You should rather update npm
```
sudo npm install -g npm@latest
```

I do not think it is a scaling problem since the chart is rewritten in every update.

**Comment by lavolp3** [comment]
> @lavolp3 Remove/rename your repository (lavolp3/MMM-AVStock) to move original to your account.

@eouia OK I have renamed the one in my account. You can move it. Are you sure it doesn't affect current users?

**Comment by eouia** [comment]
@lavolp3 Yes. It will be auto-transferred and re-routed.

**Comment by lavolp3** [comment]
@eouia I have deleted my repo now. You can transfer it.

**Comment by svlstriker** [comment]
hmmm... I did a complete new installation and added this module first to check, if any other installations break anything... but the problem is still the same...

did you had the time to check master branch and series mode with LHA.DE as symbol?

**Comment by lavolp3** [comment]
@svlstriker Not yet. Will check soon, now that the module has been transferred

**Comment by lavolp3** [comment]
OK I did a reinstall of the master branch and cannot confirm your error.
![image](https://user-images.githubusercontent.com/20084205/81536224-7ad84900-936b-11ea-919d-2dbe4e1c367a.png)

I believe part of the reason may be that this is a german stock.
I'll implement a debug function and then we can test with the data thrown out by the debug function.

Will let you know as soon as it's implemented.

**Comment by svlstriker** [comment]
okay... within my 3rd reinstall i try it again with default english language...
maybe there is an issue... if not I will also change the system language to english as well and check again...

tell me, if I should test anything else for you

**Comment by lavolp3** [comment]
No need to do that. I'm in Germany.

**Comment by lavolp3** [comment]
OK, please do a `git pull` and include into your config
```
debug: true
```

Also, don't forget to restart the mirror via `pm2 restart mm` or however you are running it.

Then you can open the dev tools in your browser (F12) and you will see the payload received from node_helper).
Can you post that please?

Thanks!

**Comment by svlstriker** [comment]
I do not know, what you mean by open the dev tools in my browser...
I run 'pm2 log mm' to see all messages produced by running magicmirror:

```
0|magicMirror  | [2020-05-11 11:39:35.924] [LOG]    [AVSTOCK] Initialized.
0|magicMirror  | [2020-05-11 11:39:35.934] [LOG]    MMM-AVStock:  Calling url : https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=LHA.DE&apikey=<my_key>
0|magicMirror  | [2020-05-11 11:39:43.606] [LOG]    
0|magicMirror  | MMM-AVStock:  [AVSTOCK] Response is parsed for LHA.DE
0|magicMirror  | [2020-05-11 11:39:43.775] [LOG]    
0|magicMirror  | MMM-AVStock:  Sending result: [{"symbol":"LHA.DE","date":"2020-05-11","open":"7.8900","high":"7.9120","low":"7.6540","close":"7.7200","volume":"2547598","hash":-2050675510,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.DE","date":"2020-05-08","open":"7.8000","high":"7.8800","low":"7.7000","close":"7.7780","volume":"5395265","hash":-2050675510,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.DE","date":"2020-05-07","open":"7.8400","high":"8.0600","low":"7.4880","close":"7.8600","volume":"11561713","hash":-2050675510,"requestTime":"11-05 11:39","candle":"up"},{"symbol":"LHA.DE","date":"2020-05-06","open":"8.1800","high":"8.2500","low":"7.8240","close":"7.8240","volume":"5746237","hash":-2050675510,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.DE","date":"2020-05-05","open":"8.1100","high":"8.2180","low":"7.8260","close":"8.1360","volume":"6345256","hash":-2050675510,"requestTime":"11-05 11:39","candle":"up"},{"symbol":"LHA.DE","date":"2020-05-04","open":"8.1740","high":"8.2480","low":"7.7520","close":"7.9160","volume":"11473836","hash":-2050675510,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.DE","date":"2020-04-30","open":"8.5000","high":"8.7360","low":"7.9080","close":"8.1580","volume":"11697482","hash":-2050675510,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.DE","date":"2020-04-29","open":"8.2040","high":"8.4800","low":"7.8360","close":"8.4800","volume":"10453080","hash":-2050675510,"requestTime":"11-05 11:39","candle":"up"},{"symbol":"LHA.DE","date":"2020-04-28","open":"8.4140","high":"8.8920","low":"7.8200","close":"8.0960","volume":"17965306","hash":-2050675510,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.DE","date":"2020-04-27","open":"7.7760","high":"7.9300","low":"7.5700","close":"7.9300","volume":"13217225","hash":-2050675510,"requestTime":"11-05 11:39","candle":"up"},{"symbol":"LHA.DE","date":"2020-04-24","open":"7.7700","high":"7.8020","low":"7.0200","close":"7.1800","volume":"21281831","hash":-2050675510,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.DE","date":"2020-04-23","open":"7.9500","high":"7.9940","low":"7.7700","close":"7.8060","volume":"7230118","hash":-2050675510,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.DE","date":"2020-04-22","open":"8.1000","high":"8.1000","low":"7.7860","close":"7.8500","volume":"10125224","hash":-2050675510,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.DE","date":"2020-04-21","open":"8.2700","high":"8.2940","low":"7.9900","close":"7.9900","volume":"9236648","hash":-2050675510,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.DE","date":"2020-04-20","open":"8.4240","high":"8.5700","low":"8.2380","close":"8.3600","volume":"7227984","hash":-2050675510,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.DE","date":"2020-04-17","open":"8.4720","high":"8.4720","low":"8.1000","close":"8.3440","volume":"12610731","hash":-2050675510,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.DE","date":"2020-04-16","open":"8.3620","high":"8.3960","low":"8.0420","close":"8.1600","volume":"8876572","hash":-2050675510,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.DE","date":"2020-04-15","open":"8.8720","high":"8.8800","low":"8.2520","close":"8.2800","volume":"10638588","hash":-2050675510,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.DE","date":"2020-04-14","open":"9.2200","high":"9.2240","low":"8.7520","close":"8.7720","volume":"8380472","hash":-2050675510,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.DE","date":"2020-04-09","open":"8.9120","high":"8.9900","low":"8.6760","close":"8.8800","volume":"8946609","hash":-2050675510,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.DE","date":"2020-04-08","open":"8.7960","high":"8.9840","low":"8.7020","close":"8.7120","volume":"8622717","hash":-2050675510,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.DE","date":"2020-04-07","open":"9.0660","high":"9.3960","low":"8.5740","close":"8.7500","volume":"14413889","hash":-2050675510,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.DE","date":"2020-04-06","open":"8.4400","high":"8.6660","low":"8.2320","close":"8.6520","volume":"9790477","hash":-2050675510,"requestTime":"11-05 11:39","candle":"up"},{"symbol":"LHA.DE","date":"2020-04-03","open":"8.0020","high":"8.2160","low":"7.8060","close":"7.9500","volume":"9320156","hash":-2050675510,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.DE","date":"2020-04-02","open":"8.1000","high":"8.1740","low":"7.8720","close":"7.9760","volume":"13362804","hash":-2050675510,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.DE","date":"2020-04-01","open":"8.4000","high":"8.4220","low":"8.0080","close":"8.0080","volume":"11949318","hash":-2050675510,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.DE","date":"2020-03-31","open":"8.9500","high":"9.0340","low":"8.4820","close":"8.5620","volume":"14047243","hash":-2050675510,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.DE","date":"2020-03-30","open":"9.2320","high":"9.3680","low":"8.5840","close":"8.6820","volume":"10659312","hash":-2050675510,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.DE","date":"2020-03-27","open":"9.4620","high":"9.5120","low":"9.0260","close":"9.0480","volume":"7970187","hash":-2050675510,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.DE","date":"2020-03-26","open":"9.4280","high":"9.7040","low":"9.1400","close":"9.7040","volume":"8766006","hash":-2050675510,"requestTime":"11-05 11:39","candle":"up"},{"symbol":"LHA.DE","date":"2020-03-25","open":"10.3900","high":"10.5400","low":"9.3000","close":"9.5820","volume":"12392896","hash":-2050675510,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.DE","date":"2020-03-24","open":"9.2360","high":"9.9040","low":"8.9200","close":"9.9040","volume":"11523980","hash":-2050675510,"requestTime":"11-05 11:39","candle":"up"},{"symbol":"LHA.DE","date":"2020-03-23","open":"9.0000","high":"9.0120","low":"8.3700","close":"8.6900","volume":"12427186","hash":-2050675510,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.DE","date":"2020-03-20","open":"9.4340","high":"9.7400","low":"9.0920","close":"9.1600","volume":"15975092","hash":-2050675510,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.DE","date":"2020-03-19","open":"8.1000","high":"9.0800","low":"8.1000","close":"8.9680","volume":"9585873","hash":-2050675510,"requestTime":"11-05 11:39","candle":"up"},{"symbol":"LHA.DE","date":"2020-03-18","open":"8.5940","high":"9.4000","low":"8.2560","close":"8.2560","volume":"10493584","hash":-2050675510,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.DE","date":"2020-03-17","open":"9.1900","high":"9.2760","low":"8.0200","close":"8.9320","volume":"14878035","hash":-2050675510,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.DE","date":"2020-03-16","open":"8.8100","high":"9.2440","low":"8.0500","close":"8.6560","volume":"27433147","hash":-2050675510,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.DE","date":"2020-03-13","open":"9.1500","high":"10.8000","low":"8.5320","close":"9.4000","volume":"31423828","hash":-2050675510,"requestTime":"11-05 11:39","candle":"up"},{"symbol":"LHA.DE","date":"2020-03-12","open":"9.4300","high":"9.5900","low":"8.7640","close":"8.7640","volume":"34502233","hash":-2050675510,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.DE","date":"2020-03-11","open":"10.7800","high":"10.8100","low":"10.0900","close":"10.1950","volume":"22769853","hash":-2050675510,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.DE","date":"2020-03-10","open":"11.0000","high":"11.3100","low":"10.4300","close":"10.4300","volume":"19017161","hash":-2050675510,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.DE","date":"2020-03-09","open":"10.8750","high":"11.6200","low":"10.5300","close":"10.5350","volume":"24955218","hash":-2050675510,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.DE","date":"2020-03-06","open":"11.1000","high":"11.6800","low":"10.7000","close":"11.4750","volume":"23119368","hash":-2050675510,"requestTime":"11-05 11:39","candle":"up"},{"symbol":"LHA.DE","date":"2020-03-05","open":"12.1150","high":"12.1350","low":"11.2100","close":"11.5000","volume":"17063913","hash":-2050675510,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.DE","date":"2020-03-04","open":"12.0700","high":"12.2850","low":"11.7800","close":"11.9450","volume":"18841084","hash":-2050675510,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.DE","date":"2020-03-03","open":"11.5000","high":"12.0950","low":"11.3500","close":"11.9000","volume":"26686475","hash":-2050675510,"requestTime":"11-05 11:39","candle":"up"},{"symbol":"LHA.DE","date":"2020-03-02","open":"11.9450","high":"11.9650","low":"10.7000","close":"10.9300","volume":"24362419","hash":-2050675510,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.DE","date":"2020-02-28","open":"11.6500","high":"12.1000","low":"11.5200","close":"11.6900","volume":"19828175","hash":-2050675510,"requestTime":"11-05 11:39","candle":"up"},{"symbol":"LHA.DE","date":"2020-02-27","open":"12.7100","high":"12.7450","low":"11.9100","close":"12.2700","volume":"19993900","hash":-2050675510,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.DE","date":"2020-02-26","open":"13.1300","high":"13.3350","low":"12.7450","close":"13.0600","volume":"14413852","hash":-2050675510,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.DE","date":"2020-02-25","open":"13.8000","high":"13.8000","low":"13.1250","close":"13.3000","volume":"11633316","hash":-2050675510,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.DE","date":"2020-02-24","open":"13.9450","high":"14.0000","low":"13.4700","close":"13.5100","volume":"19306507","hash":-2050675510,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.DE","date":"2020-02-21","open":"14.8850","high":"14.9650","low":"14.7200","close":"14.8150","volume":"5430244","hash":-2050675510,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.DE","date":"2020-02-20","open":"15.2800","high":"15.3400","low":"14.8250","close":"15.0150","volume":"9228166","hash":-2050675510,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.DE","date":"2020-02-19","open":"15.3600","high":"15.4400","low":"15.3050","close":"15.4000","volume":"4212416","hash":-2050675510,"requestTime":"11-05 11:39","candle":"up"},{"symbol":"LHA.DE","date":"2020-02-18","open":"15.1350","high":"15.2900","low":"15.0800","close":"15.2900","volume":"3004989","hash":-2050675510,"requestTime":"11-05 11:39","candle":"up"},{"symbol":"LHA.DE","date":"2020-02-17","open":"15.3400","high":"15.4000","low":"15.2500","close":"15.3000","volume":"3347057","hash":-2050675510,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.DE","date":"2020-02-14","open":"15.2500","high":"15.4250","low":"15.1900","close":"15.2100","volume":"3379814","hash":-2050675510,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.DE","date":"2020-02-13","open":"15.2000","high":"15.2500","low":"14.9900","close":"15.2100","volume":"5600865","hash":-2050675510,"requestTime":"11-05 11:39","candle":"up"},{"symbol":"LHA.DE","date":"2020-02-12","open":"15.0850","high":"15.4650","low":"15.0200","close":"15.3700","volume":"6575110","hash":-2050675510,"requestTime":"11-05 11:39","candle":"up"},{"symbol":"LHA.DE","date":"2020-02-11","open":"14.6200","high":"15.0550","low":"14.5950","close":"15.0550","volume":"5339126","hash":-2050675510,"requestTime":"11-05 11:39","candle":"up"},{"symbol":"LHA.DE","date":"2020-02-10","open":"14.6300","high":"14.6850","low":"14.4750","close":"14.4900","volume":"4280303","hash":-2050675510,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.DE","date":"2020-02-07","open":"14.8850","high":"14.9150","low":"14.4750","close":"14.6900","volume":"6528384","hash":-2050675510,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.DE","date":"2020-02-06","open":"15.1550","high":"15.2500","low":"14.9850","close":"15.0000","volume":"4975426","hash":-2050675510,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.DE","date":"2020-02-05","open":"14.5500","high":"15.4650","low":"14.4700","close":"15.0350","volume":"12671893","hash":-2050675510,"requestTime":"11-05 11:39","candle":"up"},{"symbol":"LHA.DE","date":"2020-02-04","open":"14.1000","high":"14.5700","low":"14.0100","close":"14.5200","volume":"6924639","hash":-2050675510,"requestTime":"11-05 11:39","candle":"up"},{"symbol":"LHA.DE","date":"2020-02-03","open":"13.8350","high":"14.0850","low":"13.7600","close":"14.0600","volume":"5808671","hash":-2050675510,"requestTime":"11-05 11:39","candle":"up"},{"symbol":"LHA.DE","date":"2020-01-31","open":"14.0900","high":"14.1750","low":"13.8050","close":"13.8300","volume":"6119463","hash":-2050675510,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.DE","date":"2020-01-30","open":"13.9600","high":"14.1050","low":"13.7800","close":"14.0300","volume":"7294274","hash":-2050675510,"requestTime":"11-05 11:39","candle":"up"},{"symbol":"LHA.DE","date":"2020-01-29","open":"14.2250","high":"14.2900","low":"14.0750","close":"14.1700","volume":"7798259","hash":-2050675510,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.DE","date":"2020-01-28","open":"13.8200","high":"14.1200","low":"13.4500","close":"14.0000","volume":"10457161","hash":-2050675510,"requestTime":"11-05 11:39","candle":"up"},{"symbol":"LHA.DE","date":"2020-01-27","open":"14.0950","high":"14.0950","low":"13.5400","close":"13.8000","volume":"12372095","hash":-2050675510,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.DE","date":"2020-01-24","open":"14.5700","high":"14.7000","low":"14.3750","close":"14.4250","volume":"5379941","hash":-2050675510,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.DE","date":"2020-01-23","open":"14.9500","high":"14.9500","low":"14.3050","close":"14.4050","volume":"9087280","hash":-2050675510,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.DE","date":"2020-01-22","open":"14.5100","high":"14.5650","low":"14.2800","close":"14.4700","volume":"4946887","hash":-2050675510,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.DE","date":"2020-01-21","open":"14.7850","high":"14.8300","low":"14.3900","close":"14.4400","volume":"8886013","hash":-2050675510,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.DE","date":"2020-01-20","open":"15.2400","high":"15.2400","low":"14.8950","close":"14.9450","volume":"6019287","hash":-2050675510,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.DE","date":"2020-01-17","open":"15.3650","high":"15.4500","low":"15.2050","close":"15.2500","volume":"4009140","hash":-2050675510,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.DE","date":"2020-01-16","open":"15.3800","high":"15.4050","low":"15.1800","close":"15.3250","volume":"3981887","hash":-2050675510,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.DE","date":"2020-01-15","open":"15.3650","high":"15.4250","low":"15.2500","close":"15.3200","volume":"3679600","hash":-2050675510,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.DE","date":"2020-01-14","open":"15.5450","high":"15.5550","low":"15.3250","close":"15.3300","volume":"4878103","hash":-2050675510,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.DE","date":"2020-01-13","open":"15.8000","high":"15.8450","low":"15.4400","close":"15.5000","volume":"6483774","hash":-2050675510,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.DE","date":"2020-01-10","open":"16.3200","high":"16.4650","low":"15.8150","close":"15.8150","volume":"5594260","hash":-2050675510,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.DE","date":"2020-01-09","open":"15.7000","high":"16.1950","low":"15.5250","close":"16.1600","volume":"8826601","hash":-2050675510,"requestTime":"11-05 11:39","candle":"up"},{"symbol":"LHA.DE","date":"2020-01-08","open":"15.1650","high":"15.5600","low":"15.0000","close":"15.5400","volume":"6750636","hash":-2050675510,"requestTime":"11-05 11:39","candle":"up"},{"symbol":"LHA.DE","date":"2020-01-07","open":"15.4900","high":"15.6450","low":"15.3650","close":"15.3650","volume":"4169914","hash":-2050675510,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.DE","date":"2020-01-06","open":"15.4250","high":"15.4450","low":"15.0800","close":"15.3400","volume":"6641199","hash":-2050675510,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.DE","date":"2020-01-03","open":"16.3000","high":"16.3350","low":"15.3100","close":"15.5900","volume":"16227652","hash":-2050675510,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.DE","date":"2020-01-02","open":"16.2650","high":"16.7750","low":"16.2500","close":"16.6800","volume":"3644014","hash":-2050675510,"requestTime":"11-05 11:39","candle":"up"}]
0|magicMirror  | [2020-05-11 11:39:51.002] [LOG]    
0|magicMirror  | MMM-AVStock:  Calling url : https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=LHA.FRK&apikey=<my_key>
0|magicMirror  | [2020-05-11 11:39:51.873] [LOG]    
0|magicMirror  | MMM-AVStock:  [AVSTOCK] Response is parsed for LHA.FRK
0|magicMirror  | [2020-05-11 11:39:51.935] [LOG]    
0|magicMirror  | MMM-AVStock:  Sending result: [{"symbol":"LHA.FRK","date":"2020-05-11","open":"7.9800","high":"7.9880","low":"7.6600","close":"7.6980","volume":"110943","hash":853571030,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.FRK","date":"2020-05-08","open":"7.9800","high":"7.9800","low":"7.7040","close":"7.7820","volume":"248414","hash":853571030,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.FRK","date":"2020-05-07","open":"7.8660","high":"8.0460","low":"7.5000","close":"7.8580","volume":"230738","hash":853571030,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.FRK","date":"2020-05-06","open":"8.1700","high":"8.2280","low":"7.8340","close":"7.9280","volume":"155475","hash":853571030,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.FRK","date":"2020-05-05","open":"8.1500","high":"8.2280","low":"7.8300","close":"8.1700","volume":"214826","hash":853571030,"requestTime":"11-05 11:39","candle":"up"},{"symbol":"LHA.FRK","date":"2020-05-04","open":"8.2900","high":"8.4380","low":"7.7680","close":"8.0420","volume":"432290","hash":853571030,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.FRK","date":"2020-04-30","open":"8.5800","high":"8.7200","low":"7.9180","close":"8.1880","volume":"255886","hash":853571030,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.FRK","date":"2020-04-29","open":"8.1700","high":"8.4980","low":"7.8400","close":"8.4140","volume":"350306","hash":853571030,"requestTime":"11-05 11:39","candle":"up"},{"symbol":"LHA.FRK","date":"2020-04-28","open":"8.1400","high":"8.8000","low":"7.8300","close":"8.0260","volume":"716240","hash":853571030,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.FRK","date":"2020-04-27","open":"7.8500","high":"8.0000","low":"7.5760","close":"7.9600","volume":"585560","hash":853571030,"requestTime":"11-05 11:39","candle":"up"},{"symbol":"LHA.FRK","date":"2020-04-24","open":"7.6500","high":"7.8000","low":"7.0200","close":"7.2580","volume":"474880","hash":853571030,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.FRK","date":"2020-04-23","open":"7.9600","high":"7.9880","low":"7.7100","close":"7.7820","volume":"187737","hash":853571030,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.FRK","date":"2020-04-22","open":"8.1200","high":"8.1540","low":"7.7880","close":"7.9380","volume":"252262","hash":853571030,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.FRK","date":"2020-04-21","open":"8.2320","high":"8.3300","low":"8.0000","close":"8.1080","volume":"260166","hash":853571030,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.FRK","date":"2020-04-20","open":"8.5000","high":"8.5620","low":"8.2440","close":"8.4380","volume":"261716","hash":853571030,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.FRK","date":"2020-04-17","open":"8.4000","high":"8.4680","low":"8.1000","close":"8.3200","volume":"142649","hash":853571030,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.FRK","date":"2020-04-16","open":"8.3000","high":"8.4600","low":"8.0440","close":"8.1600","volume":"251664","hash":853571030,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.FRK","date":"2020-04-15","open":"8.9000","high":"8.9100","low":"8.2600","close":"8.3760","volume":"314772","hash":853571030,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.FRK","date":"2020-04-14","open":"9.3900","high":"9.3900","low":"8.7600","close":"8.8960","volume":"652659","hash":853571030,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.FRK","date":"2020-04-09","open":"8.9280","high":"8.9900","low":"8.6800","close":"8.9280","volume":"280964","hash":853571030,"requestTime":"11-05 11:39","candle":"up"},{"symbol":"LHA.FRK","date":"2020-04-08","open":"8.8380","high":"8.9780","low":"8.6400","close":"8.7600","volume":"186266","hash":853571030,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.FRK","date":"2020-04-07","open":"8.8980","high":"9.3820","low":"8.6000","close":"8.8380","volume":"420856","hash":853571030,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.FRK","date":"2020-04-06","open":"8.4800","high":"8.7500","low":"8.2400","close":"8.7500","volume":"295436","hash":853571030,"requestTime":"11-05 11:39","candle":"up"},{"symbol":"LHA.FRK","date":"2020-04-03","open":"8.0300","high":"8.2040","low":"7.8060","close":"8.0180","volume":"326076","hash":853571030,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.FRK","date":"2020-04-02","open":"8.0900","high":"8.1680","low":"7.8780","close":"7.9600","volume":"392551","hash":853571030,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.FRK","date":"2020-04-01","open":"8.4000","high":"8.5500","low":"8.0120","close":"8.1260","volume":"309907","hash":853571030,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.FRK","date":"2020-03-31","open":"8.8700","high":"9.1100","low":"8.5000","close":"8.6400","volume":"311621","hash":853571030,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.FRK","date":"2020-03-30","open":"9.5000","high":"9.5100","low":"8.6000","close":"8.7980","volume":"242130","hash":853571030,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.FRK","date":"2020-03-27","open":"9.7100","high":"9.7480","low":"9.0400","close":"9.2160","volume":"180366","hash":853571030,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.FRK","date":"2020-03-26","open":"9.4800","high":"9.8000","low":"9.1760","close":"9.8000","volume":"149698","hash":853571030,"requestTime":"11-05 11:39","candle":"up"},{"symbol":"LHA.FRK","date":"2020-03-25","open":"10.2000","high":"10.5850","low":"9.2980","close":"10.0250","volume":"615814","hash":853571030,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.FRK","date":"2020-03-24","open":"9.2700","high":"9.8480","low":"8.9500","close":"9.6100","volume":"227236","hash":853571030,"requestTime":"11-05 11:39","candle":"up"},{"symbol":"LHA.FRK","date":"2020-03-23","open":"8.8000","high":"9.0300","low":"8.4000","close":"8.9000","volume":"243056","hash":853571030,"requestTime":"11-05 11:39","candle":"up"},{"symbol":"LHA.FRK","date":"2020-03-20","open":"9.4500","high":"9.6980","low":"9.1000","close":"9.2000","volume":"242974","hash":853571030,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.FRK","date":"2020-03-19","open":"8.7000","high":"9.1480","low":"8.4820","close":"9.1480","volume":"237213","hash":853571030,"requestTime":"11-05 11:39","candle":"up"},{"symbol":"LHA.FRK","date":"2020-03-18","open":"8.4000","high":"9.3440","low":"8.1000","close":"8.2800","volume":"233902","hash":853571030,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.FRK","date":"2020-03-17","open":"9.1400","high":"9.2200","low":"8.0260","close":"8.9500","volume":"243274","hash":853571030,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.FRK","date":"2020-03-16","open":"8.9000","high":"9.1800","low":"8.0640","close":"8.6040","volume":"388768","hash":853571030,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.FRK","date":"2020-03-13","open":"9.0600","high":"10.7400","low":"8.5500","close":"9.6480","volume":"416149","hash":853571030,"requestTime":"11-05 11:39","candle":"up"},{"symbol":"LHA.FRK","date":"2020-03-12","open":"9.6500","high":"9.7780","low":"8.8040","close":"9.0080","volume":"522466","hash":853571030,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.FRK","date":"2020-03-11","open":"10.6000","high":"10.7800","low":"10.1000","close":"10.1500","volume":"183146","hash":853571030,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.FRK","date":"2020-03-10","open":"11.2500","high":"11.2900","low":"10.4400","close":"10.9100","volume":"220203","hash":853571030,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.FRK","date":"2020-03-09","open":"11.0400","high":"11.6100","low":"10.5000","close":"10.5500","volume":"335138","hash":853571030,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.FRK","date":"2020-03-06","open":"11.2800","high":"11.5900","low":"10.7150","close":"11.4200","volume":"229698","hash":853571030,"requestTime":"11-05 11:39","candle":"up"},{"symbol":"LHA.FRK","date":"2020-03-05","open":"12.2300","high":"12.2300","low":"11.2300","close":"11.4500","volume":"137872","hash":853571030,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.FRK","date":"2020-03-04","open":"12.0400","high":"12.2700","low":"11.8100","close":"12.1450","volume":"207216","hash":853571030,"requestTime":"11-05 11:39","candle":"up"},{"symbol":"LHA.FRK","date":"2020-03-03","open":"11.4400","high":"12.0900","low":"11.3800","close":"11.9050","volume":"299783","hash":853571030,"requestTime":"11-05 11:39","candle":"up"},{"symbol":"LHA.FRK","date":"2020-03-02","open":"11.9700","high":"12.1800","low":"10.7150","close":"11.2850","volume":"309100","hash":853571030,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.FRK","date":"2020-02-28","open":"11.6000","high":"12.0850","low":"11.5450","close":"11.6800","volume":"178886","hash":853571030,"requestTime":"11-05 11:39","candle":"up"},{"symbol":"LHA.FRK","date":"2020-02-27","open":"12.8300","high":"12.8350","low":"11.9300","close":"12.2900","volume":"241680","hash":853571030,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.FRK","date":"2020-02-26","open":"13.1150","high":"13.3150","low":"12.7650","close":"12.8550","volume":"162398","hash":853571030,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.FRK","date":"2020-02-25","open":"13.8200","high":"13.9100","low":"13.1250","close":"13.3100","volume":"120377","hash":853571030,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.FRK","date":"2020-02-24","open":"14.3700","high":"14.4200","low":"13.4900","close":"13.6100","volume":"233490","hash":853571030,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.FRK","date":"2020-02-21","open":"15.0000","high":"15.0100","low":"14.7500","close":"14.7750","volume":"34285","hash":853571030,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.FRK","date":"2020-02-20","open":"15.3800","high":"15.3850","low":"14.8500","close":"15.0450","volume":"42011","hash":853571030,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.FRK","date":"2020-02-19","open":"15.3250","high":"15.4700","low":"15.3150","close":"15.4350","volume":"28906","hash":853571030,"requestTime":"11-05 11:39","candle":"up"},{"symbol":"LHA.FRK","date":"2020-02-18","open":"15.2000","high":"15.3100","low":"15.0300","close":"15.2750","volume":"22668","hash":853571030,"requestTime":"11-05 11:39","candle":"up"},{"symbol":"LHA.FRK","date":"2020-02-17","open":"15.3000","high":"15.4000","low":"15.2700","close":"15.3300","volume":"39652","hash":853571030,"requestTime":"11-05 11:39","candle":"up"},{"symbol":"LHA.FRK","date":"2020-02-14","open":"15.1950","high":"15.4200","low":"15.1700","close":"15.2000","volume":"30635","hash":853571030,"requestTime":"11-05 11:39","candle":"up"},{"symbol":"LHA.FRK","date":"2020-02-13","open":"15.3300","high":"15.3300","low":"15.0000","close":"15.1600","volume":"25622","hash":853571030,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.FRK","date":"2020-02-12","open":"15.1000","high":"15.4550","low":"15.0700","close":"15.4100","volume":"47410","hash":853571030,"requestTime":"11-05 11:39","candle":"up"},{"symbol":"LHA.FRK","date":"2020-02-11","open":"14.6500","high":"15.0450","low":"14.6200","close":"15.0000","volume":"36041","hash":853571030,"requestTime":"11-05 11:39","candle":"up"},{"symbol":"LHA.FRK","date":"2020-02-10","open":"14.7100","high":"14.7350","low":"14.5000","close":"14.5500","volume":"16724","hash":853571030,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.FRK","date":"2020-02-07","open":"15.0350","high":"15.0450","low":"14.4800","close":"14.6500","volume":"27991","hash":853571030,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.FRK","date":"2020-02-06","open":"15.2000","high":"15.2500","low":"14.9900","close":"15.0550","volume":"35196","hash":853571030,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.FRK","date":"2020-02-05","open":"14.5350","high":"15.4400","low":"14.4750","close":"15.0250","volume":"84977","hash":853571030,"requestTime":"11-05 11:39","candle":"up"},{"symbol":"LHA.FRK","date":"2020-02-04","open":"14.1700","high":"14.5650","low":"14.0300","close":"14.4500","volume":"39223","hash":853571030,"requestTime":"11-05 11:39","candle":"up"},{"symbol":"LHA.FRK","date":"2020-02-03","open":"13.9200","high":"14.1150","low":"13.7700","close":"14.0500","volume":"50121","hash":853571030,"requestTime":"11-05 11:39","candle":"up"},{"symbol":"LHA.FRK","date":"2020-01-31","open":"14.0400","high":"14.1350","low":"13.7350","close":"13.7350","volume":"49863","hash":853571030,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.FRK","date":"2020-01-30","open":"14.0800","high":"14.0900","low":"13.7800","close":"14.0550","volume":"64076","hash":853571030,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.FRK","date":"2020-01-29","open":"14.3050","high":"14.3050","low":"14.0850","close":"14.2550","volume":"73385","hash":853571030,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.FRK","date":"2020-01-28","open":"13.9400","high":"14.1400","low":"13.4550","close":"14.1100","volume":"69917","hash":853571030,"requestTime":"11-05 11:39","candle":"up"},{"symbol":"LHA.FRK","date":"2020-01-27","open":"14.2150","high":"14.2150","low":"13.5400","close":"13.9150","volume":"155875","hash":853571030,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.FRK","date":"2020-01-24","open":"14.5250","high":"14.6950","low":"14.3900","close":"14.5300","volume":"25939","hash":853571030,"requestTime":"11-05 11:39","candle":"up"},{"symbol":"LHA.FRK","date":"2020-01-23","open":"14.9500","high":"15.0000","low":"14.3150","close":"14.5050","volume":"82608","hash":853571030,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.FRK","date":"2020-01-22","open":"14.5500","high":"14.8200","low":"14.3600","close":"14.7950","volume":"83036","hash":853571030,"requestTime":"11-05 11:39","candle":"up"},{"symbol":"LHA.FRK","date":"2020-01-21","open":"14.8200","high":"14.8850","low":"14.3900","close":"14.4850","volume":"64170","hash":853571030,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.FRK","date":"2020-01-20","open":"15.1900","high":"15.2500","low":"14.9000","close":"15.0100","volume":"88038","hash":853571030,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.FRK","date":"2020-01-17","open":"15.3600","high":"15.4050","low":"15.2200","close":"15.2800","volume":"32722","hash":853571030,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.FRK","date":"2020-01-16","open":"15.3150","high":"15.4300","low":"15.1900","close":"15.3450","volume":"20817","hash":853571030,"requestTime":"11-05 11:39","candle":"up"},{"symbol":"LHA.FRK","date":"2020-01-15","open":"15.3500","high":"15.4400","low":"15.2700","close":"15.4000","volume":"15161","hash":853571030,"requestTime":"11-05 11:39","candle":"up"},{"symbol":"LHA.FRK","date":"2020-01-14","open":"15.6550","high":"15.6550","low":"15.3100","close":"15.4400","volume":"33223","hash":853571030,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.FRK","date":"2020-01-13","open":"15.9800","high":"16.0100","low":"15.4450","close":"15.5500","volume":"42169","hash":853571030,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.FRK","date":"2020-01-10","open":"16.1400","high":"16.4600","low":"15.8000","close":"15.9050","volume":"39002","hash":853571030,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.FRK","date":"2020-01-09","open":"15.6600","high":"16.2350","low":"15.5450","close":"16.0500","volume":"68074","hash":853571030,"requestTime":"11-05 11:39","candle":"up"},{"symbol":"LHA.FRK","date":"2020-01-08","open":"15.1700","high":"15.6500","low":"15.0200","close":"15.5450","volume":"45150","hash":853571030,"requestTime":"11-05 11:39","candle":"up"},{"symbol":"LHA.FRK","date":"2020-01-07","open":"15.4500","high":"15.6200","low":"15.3900","close":"15.4150","volume":"48530","hash":853571030,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.FRK","date":"2020-01-06","open":"15.5000","high":"15.5200","low":"15.1000","close":"15.4050","volume":"49869","hash":853571030,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.FRK","date":"2020-01-03","open":"16.3300","high":"16.3300","low":"15.3300","close":"15.6400","volume":"114285","hash":853571030,"requestTime":"11-05 11:39","candle":"down"},{"symbol":"LHA.FRK","date":"2020-01-02","open":"16.2850","high":"16.7750","low":"16.2850","close":"16.7100","volume":"13506","hash":853571030,"requestTime":"11-05 11:39","candle":"up"}]
```

Is this kind of, what you need?

**Comment by lavolp3** [comment]
Please hold for a moment, I found an issue in the calculation of the chart data!

**Comment by lavolp3** [comment]
I have fixed an issue in the scaling calculation and pushed it. Please pull and try again. Also restart the mirror.

Hopefully this issue will get solved.

**Comment by svlstriker** [comment]
except for the loss of value of LHA it looks awesome, thank you!

**Comment by lavolp3** [comment]
Great!
Stay tuned for further updates. 
I'll include EMA/SMA's (so you know when to buy again :-) ) and try to build a combination of table and chart.

**Comment by svlstriker** [comment]
ah... just saw, that the colored candles still do not work...

**Comment by lavolp3** [comment]
did you set 
```
coloredCandles: true
```
in your config?
Please post again.

**Comment by svlstriker** [comment]
```
		{
			module: "MMM-AVStock",
			position: "top_right",
			config: {
				apiKey : "<key>",
				symbols : ["LHA.DE", "LHA.FRK"],
				alias : ["Lufthansa DE", "Lufthansa FFM"],
				mode : "series",
				candleSticks : true,
				coloredCandles : true,
			}
		},
```
